output = [{'ilvl': 85, 'enhance': 15, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 500},
           'subs': [{'stat': 'HPP', 'value': 16}, {'stat': 'AtkP', 'value': 22}, {'stat': 'Spd', 'value': 4},
                    {'stat': 'CChance', 'value': 3}], 'set': 'Lifesteal'},
          {'ilvl': 70, 'enhance': 15, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 440},
           'subs': [{'stat': 'AtkP', 'value': 7}, {'stat': 'Spd', 'value': 10}, {'stat': 'CChance', 'value': 10},
                    {'stat': 'Eff', 'value': 11}], 'set': 'Attack'},
          {'ilvl': 55, 'enhance': 15, 'grade': 'Epic', 'slot': 'Ve', 'main': {'stat': 'Atk', 'value': 330},
           'subs': [{'stat': 'AtkP', 'value': 10}, {'stat': 'Spd', 'value': 7}, {'stat': 'CChance', 'value': 8},
                    {'stat': 'Eff', 'value': 9}], 'set': 'Destruction'},
          {'ilvl': 67, 'enhance': 0, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 85},
           'subs': [{'stat': 'HPP', 'value': 7}, {'stat': 'AtkP', 'value': 7}, {'stat': 'CChance', 'value': 4},
                    {'stat': 'CDmg', 'value': 6}], 'set': 'Rage'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 500},
           'subs': [{'stat': 'CChance', 'value': 9}, {'stat': 'AtkP', 'value': 13}, {'stat': 'HPP', 'value': 11},
                    {'stat': 'CDmg', 'value': 16}], 'set': 'Speed'},
          {'ilvl': 88, 'enhance': 3, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 164},
           'subs': [{'stat': 'Spd', 'value': 3}, {'stat': 'CChance', 'value': 5}, {'stat': 'HPP', 'value': 11},
                    {'stat': 'CDmg', 'value': 6}], 'set': 'Health'},
          {'ilvl': 70, 'enhance': 15, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 440},
           'subs': [{'stat': 'CChance', 'value': 8}, {'stat': 'HPP', 'value': 17}, {'stat': 'Eff', 'value': 12},
                    {'stat': 'CDmg', 'value': 9}], 'set': 'Critical'},
          {'ilvl': 85, 'enhance': 4, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 100},
           'subs': [{'stat': 'Res', 'value': 6}, {'stat': 'CChance', 'value': 5}, {'stat': 'Spd', 'value': 4},
                    {'stat': 'HPP', 'value': 5}], 'set': 'Speed'},
          {'ilvl': 85, 'enhance': 5, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 200},
           'subs': [{'stat': 'Spd', 'value': 4}, {'stat': 'HP', 'value': 161}, {'stat': 'CChance', 'value': 8},
                    {'stat': 'CDmg', 'value': 4}], 'set': 'Hit'},
          {'ilvl': 70, 'enhance': 9, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 246},
           'subs': [{'stat': 'HPP', 'value': 9}, {'stat': 'Spd', 'value': 3}, {'stat': 'Res', 'value': 9},
                    {'stat': 'Eff', 'value': 11}], 'set': 'Health'},
          {'ilvl': 85, 'enhance': 17, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 360},
           'subs': [{'stat': 'Res', 'value': 17}, {'stat': 'Spd', 'value': 2}, {'stat': 'AtkP', 'value': 18},
                    {'stat': 'Eff', 'value': 6}], 'set': 'Attack'},
          {'ilvl': 70, 'enhance': 7, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 211},
           'subs': [{'stat': 'CDmg', 'value': 8}, {'stat': 'Spd', 'value': 6}, {'stat': 'CChance', 'value': 2},
                    {'stat': 'Res', 'value': 5}], 'set': 'Speed'},
          {'ilvl': 70, 'enhance': 17, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 316},
           'subs': [{'stat': 'AtkP', 'value': 5}, {'stat': 'Spd', 'value': 7}, {'stat': 'CChance', 'value': 2},
                    {'stat': 'Eff', 'value': 14}], 'set': 'Hit'},
          {'ilvl': 70, 'enhance': 17, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 316},
           'subs': [{'stat': 'Eff', 'value': 5}, {'stat': 'CChance', 'value': 9}, {'stat': 'CDmg', 'value': 6},
                    {'stat': 'HPP', 'value': 14}], 'set': 'Destruction'},
          {'ilvl': 70, 'enhance': 15, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 440},
           'subs': [{'stat': 'Spd', 'value': 5}, {'stat': 'Eff', 'value': 18}, {'stat': 'AtkP', 'value': 13},
                    {'stat': 'CDmg', 'value': 6}], 'set': 'Destruction'},
          {'ilvl': 70, 'enhance': 9, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 246},
           'subs': [{'stat': 'AtkP', 'value': 16}, {'stat': 'HP', 'value': 319}, {'stat': 'HPP', 'value': 6},
                    {'stat': 'Spd', 'value': 2}], 'set': 'Counter'},
          {'ilvl': 88, 'enhance': 3, 'grade': 'Epic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 164},
           'subs': [{'stat': 'HPP', 'value': 6}, {'stat': 'Spd', 'value': 4}, {'stat': 'Res', 'value': 10},
                    {'stat': 'Eff', 'value': 5}], 'set': 'Hit'},
          {'ilvl': 85, 'enhance': 77, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 330},
           'subs': [{'stat': 'AtkP', 'value': 18}, {'stat': 'Spd', 'value': 2}, {'stat': 'Eff', 'value': 9}],
           'set': 'Hit'},
          {'ilvl': 85, 'enhance': 9, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 280},
           'subs': [{'stat': 'Eff', 'value': 12}, {'stat': 'Res', 'value': 7}, {'stat': 'AtkP', 'value': 17}],
           'set': 'Speed'},
          {'ilvl': 85, 'enhance': 17, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 360},
           'subs': [{'stat': 'Eff', 'value': 6}, {'stat': 'Spd', 'value': 2}, {'stat': 'HPP', 'value': 24},
                    {'stat': 'Res', 'value': 6}], 'set': 'Critical'},
          {'ilvl': 85, 'enhance': 0, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 180},
           'subs': [{'stat': 'Spd', 'value': 3}, {'stat': 'AtkP', 'value': 5}, {'stat': 'HPP', 'value': 12}],
           'set': 'Hit'},
          {'ilvl': 85, 'enhance': 5, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 200},
           'subs': [{'stat': 'AtkP', 'value': 7}, {'stat': 'CChance', 'value': 9}, {'stat': 'Spd', 'value': 4}],
           'set': 'Speed'},
          {'ilvl': 85, 'enhance': 4, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 100},
           'subs': [{'stat': 'Spd', 'value': 2}, {'stat': 'AtkP', 'value': 6}, {'stat': 'Eff', 'value': 7}],
           'set': 'Speed'},
          {'ilvl': 85, 'enhance': 4, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 100},
           'subs': [{'stat': 'CChance', 'value': 4}, {'stat': 'HPP', 'value': 7}, {'stat': 'AtkP', 'value': 4}],
           'set': 'Speed'},
          {'ilvl': 85, 'enhance': 4, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 100},
           'subs': [{'stat': 'Spd', 'value': 2}, {'stat': 'AtkP', 'value': 4}, {'stat': 'HPP', 'value': 6}],
           'set': 'Speed'},
          {'ilvl': 85, 'enhance': 14, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 420},
           'subs': [{'stat': 'Eff', 'value': 12}, {'stat': 'Res', 'value': 16}, {'stat': 'Spd', 'value': 2},
                    {'stat': 'AtkP', 'value': 4}], 'set': 'Defense'},
          {'ilvl': 85, 'enhance': 13, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 390},
           'subs': [{'stat': 'HPP', 'value': 13}, {'stat': 'AtkP', 'value': 9}, {'stat': 'Eff', 'value': 11},
                    {'stat': 'Spd', 'value': 4}], 'set': 'Attack'},
          {'ilvl': 85, 'enhance': 17, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 360},
           'subs': [{'stat': 'HPP', 'value': 15}, {'stat': 'AtkP', 'value': 12}, {'stat': 'CChance', 'value': 9},
                    {'stat': 'Eff', 'value': 8}], 'set': 'Attack'},
          {'ilvl': 70, 'enhance': 8, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 228},
           'subs': [{'stat': 'HPP', 'value': 13}, {'stat': 'Eff', 'value': 10}, {'stat': 'CChance', 'value': 3}],
           'set': 'Immunity'},
          {'ilvl': 70, 'enhance': 14, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 369},
           'subs': [{'stat': 'Spd', 'value': 6}, {'stat': 'CDmg', 'value': 11}, {'stat': 'AtkP', 'value': 7},
                    {'stat': 'Res', 'value': 4}], 'set': 'Attack'},
          {'ilvl': 70, 'enhance': 77, 'grade': 'Heroic', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 290},
           'subs': [{'stat': 'CChance', 'value': 4}, {'stat': 'CDmg', 'value': 3}, {'stat': 'HPP', 'value': 22}],
           'set': 'Attack'},
          {'ilvl': 85, 'enhance': 77, 'grade': 'Rare', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 330},
           'subs': [{'stat': 'Spd', 'value': 10}, {'stat': 'AtkP', 'value': 6}, {'stat': 'Res', 'value': 7}],
           'set': 'Speed'},
          {'ilvl': 85, 'enhance': 10, 'grade': 'Rare', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 300},
           'subs': [{'stat': 'AtkP', 'value': 4}, {'stat': 'CChance', 'value': 10}, {'stat': 'CDmg', 'value': 5}],
           'set': 'Hit'},
          {'ilvl': 85, 'enhance': 17, 'grade': 'Rare', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 360},
           'subs': [{'stat': 'CChance', 'value': 9}, {'stat': 'AtkP', 'value': 5}, {'stat': 'CDmg', 'value': 5},
                    {'stat': 'HP', 'value': 158}], 'set': 'Attack'},
          {'ilvl': 70, 'enhance': 0, 'grade': 'Rare', 'slot': 'Weapon', 'main': {'stat': 'Atk', 'value': 88},
           'subs': [{'stat': 'CChance', 'value': 4}, {'stat': 'Spd', 'value': 3}], 'set': 'Immunity'},
          {'ilvl': 71, 'enhance': 15, 'grade': 'Foic', 'slot': 'Delet', 'main': {'stat': 'HP', 'value': 2360},
           'subs': [{'stat': 'HPP', 'value': 16}, {'stat': 'AtkP', 'value': 11}, {'stat': 'CChance', 'value': 4},
                    {'stat': 'Eff', 'value': 18}], 'set': 'Attack'},
          {'ilvl': 70, 'enhance': 15, 'grade': 'Epic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 2360},
           'subs': [{'stat': 'AtkP', 'value': 18}, {'stat': 'Spd', 'value': 4}, {'stat': 'CChance', 'value': 8},
                    {'stat': 'CDmg', 'value': 14}], 'set': 'Attack'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Epic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 2700},
           'subs': [{'stat': 'HPP', 'value': 17}, {'stat': 'AtkP', 'value': 9}, {'stat': 'Spd', 'value': 8},
                    {'stat': 'CChance', 'value': 4}], 'set': 'Lifesteal'},
          {'ilvl': 70, 'enhance': 68, 'grade': 'Epic', 'slot': 'Elmet', 'main': {'stat': 'HP', 'value': 1227},
           'subs': [{'stat': 'CChance', 'value': 4}, {'stat': 'Spd', 'value': 3}, {'stat': 'CDmg', 'value': 3},
                    {'stat': 'Eff', 'value': 15}], 'set': 'Critical'},
          {'ilvl': 70, 'enhance': 15, 'grade': 'Epic', 'slot': 'Elmet', 'main': {'stat': 'HP', 'value': 2360},
           'subs': [{'stat': 'CDmg', 'value': 6}, {'stat': 'Eff', 'value': 12}, {'stat': 'AtkP', 'value': 24},
                    {'stat': 'CChance', 'value': 6}], 'set': 'Speed'},
          {'ilvl': 88, 'enhance': 15, 'grade': 'Epic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 2765},
           'subs': [{'stat': 'HPP', 'value': 18}, {'stat': 'DefP', 'value': 19}, {'stat': 'Spd', 'value': 4},
                    {'stat': 'Res', 'value': 10}], 'set': 'Speed'},
          {'ilvl': 88, 'enhance': 0, 'grade': 'Epic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 553},
           'subs': [{'stat': 'AtkP', 'value': 6}, {'stat': 'Spd', 'value': 4}, {'stat': 'CChance', 'value': 5},
                    {'stat': 'Res', 'value': 6}], 'set': 'Hit'},
          {'ilvl': 70, 'enhance': 0, 'grade': 'Epic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 472},
           'subs': [{'stat': 'Eff', 'value': 7}, {'stat': 'Atk', 'value': 29}, {'stat': 'Spd', 'value': 3},
                    {'stat': 'AtkP', 'value': 1}], 'set': 'Lifesteal'},
          {'ilvl': 70, 'enhance': 10, 'grade': 'Epic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 1416},
           'subs': [{'stat': 'CChance', 'value': 5}, {'stat': 'HPP', 'value': 17}, {'stat': 'Eff', 'value': 4},
                    {'stat': 'Spd', 'value': 2}], 'set': 'Destruction'},
          {'ilvl': 85, 'enhance': 0, 'grade': 'Epic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 540},
           'subs': [{'stat': 'Spd', 'value': 3}, {'stat': 'Res', 'value': 5}, {'stat': 'Eff', 'value': 6},
                    {'stat': 'DefP', 'value': 6}], 'set': 'Counter'},
          {'ilvl': 85, 'enhance': 7, 'grade': 'Heroic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 1296},
           'subs': [{'stat': 'Res', 'value': 16}, {'stat': 'DefP', 'value': 8}, {'stat': 'Eff', 'value': 7}],
           'set': 'Speed'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Heroic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 2700},
           'subs': [{'stat': 'CDmg', 'value': 13}, {'stat': 'Def', 'value': 26}, {'stat': 'AtkP', 'value': 20},
                    {'stat': 'CChance', 'value': 5}], 'set': 'Hit'},
          {'ilvl': 0, 'enhance': 15, 'grade': 'Epic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 2765},
           'subs': [{'stat': 'AtkP', 'value': 17}, {'stat': 'Spd', 'value': 8}, {'stat': 'Res', 'value': 5},
                    {'stat': 'Eff', 'value': 10}], 'set': 'Attack'},
          {'ilvl': 85, 'enhance': 0, 'grade': 'Epic', 'slot': 'Tsimet', 'main': {'stat': 'HP', 'value': 540},
           'subs': [{'stat': 'HPP', 'value': 7}, {'stat': 'Eff', 'value': 4}, {'stat': 'CDmg', 'value': 6},
                    {'stat': 'Spd', 'value': 3}], 'set': 'Immunity'},
          {'ilvl': 70, 'enhance': 15, 'grade': 'Heroic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 2360},
           'subs': [{'stat': 'CDmg', 'value': 12}, {'stat': 'Eff', 'value': 4}, {'stat': 'CChance', 'value': 12},
                    {'stat': 'Def', 'value': 27}], 'set': 'Speed'},
          {'ilvl': 70, 'enhance': 14, 'grade': 'Heroic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 1982},
           'subs': [{'stat': 'CDmg', 'value': 10}, {'stat': 'CChance', 'value': 8}, {'stat': 'HPP', 'value': 12},
                    {'stat': 'Eff', 'value': 6}], 'set': 'Critical'},
          {'ilvl': 70, 'enhance': 77, 'grade': 'Heroic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 1557},
           'subs': [{'stat': 'HPP', 'value': 15}, {'stat': 'CChance', 'value': 5}, {'stat': 'AtkP', 'value': 5}],
           'set': 'Speed'},
          {'ilvl': 70, 'enhance': 17, 'grade': 'Heroic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 1699},
           'subs': [{'stat': 'Res', 'value': 10}, {'stat': 'Spd', 'value': 4}, {'stat': 'HPP', 'value': 8},
                    {'stat': 'AtkP', 'value': 5}], 'set': 'Speed'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Heroic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 2700},
           'subs': [{'stat': 'CChance', 'value': 5}, {'stat': 'AtkP', 'value': 21}, {'stat': 'Spd', 'value': 12},
                    {'stat': 'CDmg', 'value': 4}], 'set': 'Defense'},
          {'ilvl': 70, 'enhance': 17, 'grade': 'Heroic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 1699},
           'subs': [{'stat': 'Eff', 'value': 6}, {'stat': 'AtkP', 'value': 10}, {'stat': 'CDmg', 'value': 9},
                    {'stat': 'Atk', 'value': 34}], 'set': 'Destruction'},
          {'ilvl': 70, 'enhance': 13, 'grade': 'Heroic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 1840},
           'subs': [{'stat': 'Eff', 'value': 12}, {'stat': 'AtkP', 'value': 13}, {'stat': 'Spd', 'value': 5},
                    {'stat': 'Def', 'value': 28}], 'set': 'Attack'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Rare', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 2700},
           'subs': [{'stat': 'AtkP', 'value': 7}, {'stat': 'CChance', 'value': 12}, {'stat': 'Def', 'value': 2},
                    {'stat': 'CDmg', 'value': 12}], 'set': 'Critical'},
          {'ilvl': 70, 'enhance': 0, 'grade': 'Heroic', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 472},
           'subs': [{'stat': 'Res', 'value': 7}, {'stat': 'HPP', 'value': 4}, {'stat': 'Eff', 'value': 5}],
           'set': 'Resist'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Rare', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 2700},
           'subs': [{'stat': 'Spd', 'value': 6}, {'stat': 'AtkP', 'value': 16}, {'stat': 'CDmg', 'value': 5},
                    {'stat': 'DefP', 'value': 4}], 'set': 'Attack'},
          {'ilvl': 70, 'enhance': 15, 'grade': 'Rare', 'slot': 'Helmet', 'main': {'stat': 'HP', 'value': 2360},
           'subs': [{'stat': 'CDmg', 'value': 8}, {'stat': 'AtkP', 'value': 9}, {'stat': 'CChance', 'value': 6},
                    {'stat': 'Eff', 'value': 6}], 'set': 'Speed'},
          {'ilvl': 85, 'enhance': 13, 'grade': 'Epic', 'slot': 'Amor', 'main': {'stat': 'Def', 'value': 234},
           'subs': [{'stat': 'Spd', 'value': 6}, {'stat': 'DefP', 'value': 15}, {'stat': 'Eff', 'value': 6},
                    {'stat': 'Res', 'value': 13}], 'set': 'Speed'},
          {'ilvl': 70, 'enhance': 17, 'grade': 'Epic', 'slot': 'Attor', 'main': {'stat': 'Def', 'value': 187},
           'subs': [{'stat': 'Eff', 'value': 17}, {'stat': 'DefP', 'value': 5}, {'stat': 'CChance', 'value': 6},
                    {'stat': 'Spd', 'value': 5}], 'set': 'Speed'},
          {'ilvl': 85, 'enhance': 14, 'grade': 'Epic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 252},
           'subs': [{'stat': 'CChance', 'value': 5}, {'stat': 'Spd', 'value': 117}, {'stat': 'Eff', 'value': 15},
                    {'stat': 'HPP', 'value': 14}], 'set': 'Counter'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Heroic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 300},
           'subs': [{'stat': 'CDmg', 'value': 11}, {'stat': 'CChance', 'value': 10}, {'stat': 'DefP', 'value': 22},
                    {'stat': 'Eff', 'value': 4}], 'set': 'Hit'},
          {'ilvl': 88, 'enhance': 15, 'grade': 'Epic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 310},
           'subs': [{'stat': 'HPP', 'value': 11}, {'stat': 'Spd', 'value': 4}, {'stat': 'CChance', 'value': 5},
                    {'stat': 'Res', 'value': 32}], 'set': 'Speed'},
          {'ilvl': 88, 'enhance': 0, 'grade': 'Epic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 62},
           'subs': [{'stat': 'DefP', 'value': 6}, {'stat': 'Spd', 'value': 4}, {'stat': 'Res', 'value': 6},
                    {'stat': 'Eff', 'value': 6}], 'set': 'Hit'},
          {'ilvl': 70, 'enhance': 15, 'grade': 'Epic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 260},
           'subs': [{'stat': 'CChance', 'value': 12}, {'stat': 'Eff', 'value': 11}, {'stat': 'HP', 'value': 170},
                    {'stat': 'CDmg', 'value': 10}], 'set': 'Destruction'},
          {'ilvl': 85, 'enhance': 6, 'grade': 'Ppi', 'slot': 'Ato', 'main': {'stat': 'Def', 'value': 132},
           'subs': [{'stat': 'HP', 'value': 186}, {'stat': 'Eff', 'value': 11}, {'stat': 'Spd', 'value': 2},
                    {'stat': 'DefP', 'value': 11}], 'set': 'Immunity'},
          {'ilvl': 85, 'enhance': 0, 'grade': 'Epic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 60},
           'subs': [{'stat': 'HP', 'value': 188}, {'stat': 'Eff', 'value': 77}, {'stat': 'Spd', 'value': 4},
                    {'stat': 'Res', 'value': 8}], 'set': 'Counter'},
          {'ilvl': 85, 'enhance': 0, 'grade': 'Heroic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 108},
           'subs': [{'stat': 'Spd', 'value': 2}, {'stat': 'Eff', 'value': 6}, {'stat': 'CChance', 'value': 10}],
           'set': 'Hit'},
          {'ilvl': 85, 'enhance': 17, 'grade': 'Heroic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 216},
           'subs': [{'stat': 'DefP', 'value': 19}, {'stat': 'HPP', 'value': 12}, {'stat': 'CDmg', 'value': 5},
                    {'stat': 'HP', 'value': 161}], 'set': 'Speed'},
          {'ilvl': 70, 'enhance': 77, 'grade': 'Heroic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 171},
           'subs': [{'stat': 'Eff', 'value': 15}, {'stat': 'HPP', 'value': 11}, {'stat': 'CChance', 'value': 2}],
           'set': 'Speed'},
          {'ilvl': 70, 'enhance': 17, 'grade': 'Heroic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 187},
           'subs': [{'stat': 'HPP', 'value': 22}, {'stat': 'Spd', 'value': 2}, {'stat': 'CChance', 'value': 3},
                    {'stat': 'Eff', 'value': 4}], 'set': 'Speed'},
          {'ilvl': 85, 'enhance': 6, 'grade': 'Heroic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 132},
           'subs': [{'stat': 'Spd', 'value': 8}, {'stat': 'HPP', 'value': 4}, {'stat': 'Res', 'value': 6}],
           'set': 'Immunity'},
          {'ilvl': 85, 'enhance': 13, 'grade': 'Heroic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 234},
           'subs': [{'stat': 'Res', 'value': 11}, {'stat': 'HPP', 'value': 16}, {'stat': 'DefP', 'value': 6},
                    {'stat': 'Eff', 'value': 4}], 'set': 'Defense'},
          {'ilvl': 85, 'enhance': 2, 'grade': 'Heroic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 84},
           'subs': [{'stat': 'Spd', 'value': 3}, {'stat': 'CDmg', 'value': 6}, {'stat': 'Eff', 'value': 7}],
           'set': 'Rage'},
          {'ilvl': 70, 'enhance': 9, 'grade': 'Heroic', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 145},
           'subs': [{'stat': 'DefP', 'value': 18}, {'stat': 'HPP', 'value': 13}, {'stat': 'Eff', 'value': 4}],
           'set': 'Health'},
          {'ilvl': 70, 'enhance': 15, 'grade': 'Rare', 'slot': 'Armor', 'main': {'stat': 'Def', 'value': 260},
           'subs': [{'stat': 'CDmg', 'value': 5}, {'stat': 'Eff', 'value': 15}, {'stat': 'CChance', 'value': 4},
                    {'stat': 'HP', 'value': 283}], 'set': 'Attack'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Ppic', 'slot': 'Nerklace', 'main': {'stat': 'AtkP', 'value': 60},
           'subs': [{'stat': 'CChance', 'value': 4}, {'stat': 'Atk', 'value': 118}, {'stat': 'HPP', 'value': 21},
                    {'stat': 'DefP', 'value': 11}], 'set': 'Speed'},
          {'ilvl': 70, 'enhance': 68, 'grade': 'Epic', 'slot': 'Necklace', 'main': {'stat': 'CDmg', 'value': 29},
           'subs': [{'stat': 'HPP', 'value': 6}, {'stat': 'CChance', 'value': 3}, {'stat': 'DefP', 'value': 14},
                    {'stat': 'HP', 'value': 143}], 'set': 'Speed'},
          {'ilvl': 70, 'enhance': 14, 'grade': 'Epic', 'slot': 'Necklace', 'main': {'stat': 'HPP', 'value': 42},
           'subs': [{'stat': 'CChance', 'value': 7}, {'stat': 'Spd', 'value': 5}, {'stat': 'AtkP', 'value': 16},
                    {'stat': 'DefP', 'value': 7}], 'set': 'Immunity'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Heroic', 'slot': 'Necklace', 'main': {'stat': 'CDmg', 'value': 65},
           'subs': [{'stat': 'CChance', 'value': 15}, {'stat': 'Spd', 'value': 2}, {'stat': 'DefP', 'value': 9},
                    {'stat': 'Res', 'value': 4}], 'set': 'Hit'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Heroic', 'slot': 'Necklace', 'main': {'stat': 'AtkP', 'value': 60},
           'subs': [{'stat': 'DefP', 'value': 14}, {'stat': 'Spd', 'value': 5}, {'stat': 'Eff', 'value': 10},
                    {'stat': 'CChance', 'value': 10}], 'set': 'Hit'},
          {'ilvl': 85, 'enhance': 17, 'grade': 'Heroic', 'slot': 'Necklace', 'main': {'stat': 'AtkP', 'value': 43},
           'subs': [{'stat': 'CChance', 'value': 9}, {'stat': 'Eff', 'value': 9}, {'stat': 'CDmg', 'value': 10},
                    {'stat': 'Def', 'value': 32}], 'set': 'Speed'},
          {'ilvl': 85, 'enhance': 14, 'grade': 'Heroic', 'slot': 'Necklace', 'main': {'stat': 'HPP', 'value': 50},
           'subs': [{'stat': 'CDmg', 'value': 7}, {'stat': 'AtkP', 'value': 19}, {'stat': 'Eff', 'value': 9},
                    {'stat': 'Atk', 'value': 42}], 'set': 'Critical'},
          {'ilvl': 70, 'enhance': 17, 'grade': 'Heroic', 'slot': 'Necklace', 'main': {'stat': 'AtkP', 'value': 36},
           'subs': [{'stat': 'CChance', 'value': 2}, {'stat': 'CDmg', 'value': 12}, {'stat': 'Eff', 'value': 11},
                    {'stat': 'Def', 'value': 23}], 'set': 'Critical'},
          {'ilvl': 70, 'enhance': 15, 'grade': 'Heroic', 'slot': 'Necklace', 'main': {'stat': 'CDmg', 'value': 55},
           'subs': [{'stat': 'CChance', 'value': 2}, {'stat': 'Eff', 'value': 4}, {'stat': 'Spd', 'value': 13},
                    {'stat': 'Atk', 'value': 34}], 'set': 'Attack'},
          {'ilvl': 85, 'enhance': 3, 'grade': 'Rare', 'slot': 'Necklace', 'main': {'stat': 'DefP', 'value': 19},
           'subs': [{'stat': 'HPP', 'value': 7}, {'stat': 'Eff', 'value': 11}], 'set': 'Speed'},
          {'ilvl': 71, 'enhance': 10, 'grade': 'Epic', 'slot': 'Ring', 'main': {'stat': 'AtkP', 'value': 30},
           'subs': [{'stat': 'HPP', 'value': 8}, {'stat': 'Spd', 'value': 6}, {'stat': 'CChance', 'value': 4},
                    {'stat': 'Eff', 'value': 13}], 'set': 'Lifesteal'},
          {'ilvl': 1, 'enhance': 15, 'grade': 'Epic', 'slot': 'Ring', 'main': {'stat': 'AtkP', 'value': 60},
           'subs': [{'stat': 'HPP', 'value': 8}, {'stat': 'Spd', 'value': 4}, {'stat': 'CChance', 'value': 20},
                    {'stat': 'Eff', 'value': 13}], 'set': 'Lifesteal'},
          {'ilvl': 70, 'enhance': 7, 'grade': 'Epic', 'slot': 'Ring', 'main': {'stat': 'AtkP', 'value': 24},
           'subs': [{'stat': 'CChance', 'value': 2}, {'stat': 'Def', 'value': 82}, {'stat': 'HPP', 'value': 7},
                    {'stat': 'Spd', 'value': 2}], 'set': 'Speed'},
          {'ilvl': 70, 'enhance': 5, 'grade': 'Heroic', 'slot': 'Ring', 'main': {'stat': 'AtkP', 'value': 20},
           'subs': [{'stat': 'CDmg', 'value': 9}, {'stat': 'CChance', 'value': 3}, {'stat': 'Eff', 'value': 6}],
           'set': 'Hit'},
          {'ilvl': 70, 'enhance': 77, 'grade': 'Heroic', 'slot': 'Ring', 'main': {'stat': 'AtkP', 'value': 33},
           'subs': [{'stat': 'Spd', 'value': 8}, {'stat': 'Res', 'value': 6}, {'stat': 'HPP', 'value': 5}],
           'set': 'Speed'},
          {'ilvl': 85, 'enhance': 3, 'grade': 'Rare', 'slot': 'Ring', 'main': {'stat': 'HPP', 'value': 19},
           'subs': [{'stat': 'Eff', 'value': 7}, {'stat': 'DefP', 'value': 8}], 'set': 'Speed'},
          {'ilvl': 85, 'enhance': 14, 'grade': 'Rare', 'slot': 'Ring', 'main': {'stat': 'AtkP', 'value': 50},
           'subs': [{'stat': 'Spd', 'value': 5}, {'stat': 'CDmg', 'value': 9}, {'stat': 'HPP', 'value': 7},
                    {'stat': 'Atk', 'value': 41}], 'set': 'Critical'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Rare', 'slot': 'Ring', 'main': {'stat': 'HPP', 'value': 60},
           'subs': [{'stat': 'DefP', 'value': 15}, {'stat': 'CDmg', 'value': 6}, {'stat': 'Spd', 'value': 4},
                    {'stat': 'Atk', 'value': 67}], 'set': 'Critical'},
          {'ilvl': 67, 'enhance': 0, 'grade': 'Rare', 'slot': 'Ring', 'main': {'stat': 'Atk', 'value': 85},
           'subs': [{'stat': 'DefP', 'value': 5}, {'stat': 'CDmg', 'value': 4}], 'set': 'Speed'},
          {'ilvl': 71, 'enhance': 15, 'grade': 'Ei', 'slot': 'Sots', 'main': {'stat': 'Spd', 'value': 35},
           'subs': [{'stat': 'HPP', 'value': 12}, {'stat': 'AtkP', 'value': 12}, {'stat': 'DefP', 'value': 22},
                    {'stat': 'CChance', 'value': 4}], 'set': 'Speed'},
          {'ilvl': 88, 'enhance': 15, 'grade': 'Epic', 'slot': 'Boots', 'main': {'stat': 'AtkP', 'value': 65},
           'subs': [{'stat': 'Spd', 'value': 7}, {'stat': 'CChance', 'value': 10}, {'stat': 'CDmg', 'value': 6},
                    {'stat': 'Res', 'value': 26}], 'set': 'Speed'},
          {'ilvl': 0, 'enhance': 15, 'grade': 'Lpic', 'slot': 'Boots', 'main': {'stat': 'AtkP', 'value': 65},
           'subs': [{'stat': 'HPP', 'value': 12}, {'stat': 'CChance', 'value': 4}, {'stat': 'CDmg', 'value': 20},
                    {'stat': 'Res', 'value': 11}], 'set': 'Attack'},
          {'ilvl': 70, 'enhance': 17, 'grade': 'Epic', 'slot': 'Soots', 'main': {'stat': 'AtkP', 'value': 36},
           'subs': [{'stat': 'Res', 'value': 10}, {'stat': 'Def', 'value': 53}, {'stat': 'CDmg', 'value': 6},
                    {'stat': 'CChance', 'value': 10}], 'set': 'Critical'},
          {'ilvl': 77, 'enhance': 15, 'grade': 'Epic', 'slot': 'Boots', 'main': {'stat': 'AtkP', 'value': 50},
           'subs': [{'stat': 'HPP', 'value': 20}, {'stat': 'Spd', 'value': 3}, {'stat': 'CChance', 'value': 9},
                    {'stat': 'Eff', 'value': 4}], 'set': 'Lifesteal'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Epic', 'slot': 'Boots', 'main': {'stat': 'AtkP', 'value': 60},
           'subs': [{'stat': 'HPP', 'value': 24}, {'stat': 'Spd', 'value': 4}, {'stat': 'CChance', 'value': 5},
                    {'stat': 'Eff', 'value': 11}], 'set': 'Lifesteal'},
          {'ilvl': 85, 'enhance': 10, 'grade': 'Cpic', 'slot': 'Boots', 'main': {'stat': 'Spd', 'value': 24},
           'subs': [{'stat': 'HPP', 'value': 4}, {'stat': 'AtkP', 'value': 8}, {'stat': 'Res', 'value': 9},
                    {'stat': 'CDmg', 'value': 20}], 'set': 'Defense'},
          {'ilvl': 70, 'enhance': 7, 'grade': 'Heroic', 'slot': 'Boots', 'main': {'stat': 'Spd', 'value': 16},
           'subs': [{'stat': 'Atk', 'value': 64}, {'stat': 'Eff', 'value': 4}, {'stat': 'AtkP', 'value': 13}],
           'set': 'Critical'},
          {'ilvl': 70, 'enhance': 13, 'grade': 'Heroic', 'slot': 'Boots', 'main': {'stat': 'AtkP', 'value': 39},
           'subs': [{'stat': 'CChance', 'value': 8}, {'stat': 'Eff', 'value': 5}, {'stat': 'Spd', 'value': 7},
                    {'stat': 'Def', 'value': 24}], 'set': 'Speed'},
          {'ilvl': 70, 'enhance': 17, 'grade': 'Heroic', 'slot': 'Boots', 'main': {'stat': 'HPP', 'value': 36},
           'subs': [{'stat': 'CChance', 'value': 7}, {'stat': 'Eff', 'value': 11}, {'stat': 'Res', 'value': 10},
                    {'stat': 'DefP', 'value': 7}], 'set': 'Health'},
          {'ilvl': 70, 'enhance': 14, 'grade': 'Heroic', 'slot': 'Boots', 'main': {'stat': 'HPP', 'value': 42},
           'subs': [{'stat': 'CDmg', 'value': 10}, {'stat': 'Atk', 'value': 64}, {'stat': 'AtkP', 'value': 11},
                    {'stat': 'Eff', 'value': 7}], 'set': 'Counter'},
          {'ilvl': 85, 'enhance': 15, 'grade': 'Rare', 'slot': 'Boots', 'main': {'stat': 'Spd', 'value': 40},
           'subs': [{'stat': 'AtkP', 'value': 12}, {'stat': 'CDmg', 'value': 9}, {'stat': 'CChance', 'value': 8},
                    {'stat': 'Res', 'value': 5}], 'set': 'Critical'},
          {'ilvl': 85, 'enhance': 13, 'grade': 'Rare', 'slot': 'Boots', 'main': {'stat': 'Spd', 'value': 31},
           'subs': [{'stat': 'AtkP', 'value': 11}, {'stat': 'Atk', 'value': 69}, {'stat': 'DefP', 'value': 5},
                    {'stat': 'CChance', 'value': 3}], 'set': 'Speed'},
          {'ilvl': 70, 'enhance': 0, 'grade': 'Rare', 'slot': 'Boots', 'main': {'stat': 'Spd', 'value': 12},
           'subs': [{'stat': 'CChance', 'value': 4}, {'stat': 'AtkP', 'value': 10}], 'set': 'Hit'},
          {'ilvl': 70, 'enhance': 14, 'grade': 'Rare', 'slot': 'Boots', 'main': {'stat': 'AtkP', 'value': 42},
           'subs': [{'stat': 'CChance', 'value': 11}, {'stat': 'Eff', 'value': 5}, {'stat': 'Def', 'value': 22},
                    {'stat': 'Atk', 'value': 28}], 'set': 'Critical'},
          {'ilvl': 70, 'enhance': 14, 'grade': 'Rare', 'slot': 'Boots', 'main': {'stat': 'Spd', 'value': 29},
           'subs': [{'stat': 'Eff', 'value': 9}, {'stat': 'AtkP', 'value': 12}, {'stat': 'HP', 'value': 142},
                    {'stat': 'Res', 'value': 5}], 'set': 'Critical'},
          {'ilvl': 70, 'enhance': 17, 'grade': 'Rare', 'slot': 'Boots', 'main': {'stat': 'Spd', 'value': 25},
           'subs': [{'stat': 'CChance', 'value': 4}, {'stat': 'CDmg', 'value': 9}, {'stat': 'AtkP', 'value': 5},
                    {'stat': 'Res', 'value': 6}], 'set': 'Critical'}]
